export const providerAccountCopy = {
  title: "Provider accounts",
  description:
    "Keep separate Codex and Claude sign-ins on this host. New agents stay pinned to the account they start with.",
  add: "Add account",
  addTitle: "Add provider account",
  editTitle: "Rename provider account",
  provider: "Provider",
  name: "Account name",
  namePlaceholder: "Work",
  create: "Create account",
  save: "Save",
  saving: "Saving…",
  system: "System account",
  systemHint: "Uses the sign-in already configured for this host.",
  account: "Account",
  hostDefault: "Host default",
  hostDefaultWithAccount: (name: string) => `Host default (${name})`,
  unavailableAccount: "Unavailable account",
  noAccounts: "No accounts are configured for this provider.",
  default: "Default",
  makeDefault: "Make default",
  signedIn: "Signed in",
  notSignedIn: "Not signed in",
  edit: "Rename",
  remove: "Remove",
  removeTitle: "Remove account?",
  removeMessage: (name: string) =>
    `Remove “${name}”? Existing agents pinned to it must be archived first.`,
  loading: "Loading provider accounts…",
  unavailable: "Connect to this host to manage provider accounts.",
  upgradeRequired: "Update this host to manage multiple provider accounts.",
  errorTitle: "Unable to load provider accounts",
  retry: "Retry",
  duplicateHint: "Names must be unique within each provider.",
  providers: {
    codex: "Codex",
    claude: "Claude",
  },
} as const;
